### PR TITLE
Fixes #147 Develop Airdrop dApp

### PR DESCRIPTION
**Pull request by pacamara**
Fixes MyBitFoundation/MyBit-Network.tech#147 Develop Airdrop dApp

Status: Ready

### Implemented and working:
* Create airdrop
* Sent Airdrops page
* Force Metamask login
* Tested against local MyBit-Chain, and ropsten

### Review notes:
Main changes from `MyBit-Trust` code in:
* [CreateNewPage/index.js](https://github.com/pacamara/MyBit-Dropzone.tech/blob/issue147_airdropDapp_4/front-end/app/containers/CreateNewPage/index.js)
* [utils/core.js](https://github.com/pacamara/MyBit-Dropzone.tech/blob/issue147_airdropDapp_4/front-end/app/utils/core.js) 
* [2_ERC20Airdrop_migration.js](https://github.com/pacamara/MyBit-Dropzone.tech/blob/issue147_airdropDapp_4/migrations/2_ERC20Airdrop_migration.js) 
* [BlockchainInfo.js](https://github.com/pacamara/MyBit-Dropzone.tech/blob/issue147_airdropDapp_4/front-end/app/components/Context/BlockchainInfo.js)
* [ERC20Airdrop.sol](https://github.com/MyBitFoundation/MyBit-Dropzone.tech/pull/4/files#diff-c7edd822a8947a03622193031c22af33)

#### Ropsten:
* Update `truffle.js` with your Infura API key
* `MyBit-Dropzone.tech $ bash compileDeployContracts.sh ropsten ropsten`
* In separate terminal:
** `MyBit-Dropzone.tech/front-end $ npm install`
** `MyBit-Dropzone.tech/front-end $ npm start`
* Open http://localhost:3000/create-new
* Log into ropsten via metamask interstitial
* From contracts deployment step, note MyBitToken contract hash and add to metamask for account 1
* "Account 1" should already have total supply of MYB from contracts deployment step
* Select "Top 100 ETH addresses" recipient from dropdown
* Send airdrop
* After airdrop completes, open Sent Airdrops page at http://localhost:3000/sent-airdrops
* Click on Etherscan link and verify airdrop completed ok

#### Local MyBit-Chain:
As above but
* Deploy MyBit-Chain per https://github.com/MyBitFoundation/hello-network
* `MyBit-Dropzone.tech $ bash compileDeployContracts.sh development private`
* Select "19 local MyBit-Chain addresses" recipient from dropdown
* Etherscan link obviously will not work, can verify airdrop completion manually through metamask

### Notes:
* UI in `front-end/`, based off `MyBit-Trust`
* Assumes intent is to airdrop MYB not ETH, as airdrop contract for ERC20 tokens.

### CODE REVIEW

**Comment by pacamara** [comment]
Screen recording of sending/verifying an airdrop on Ropsten: 

airdrop-demo180d

**Comment by jjperezaguinaga** [comment]
This looks very well done and detailed @pacamara , thank you very much! Do you have a preview URL we could maybe review the project with it, or just a link to its README to know how to bootstrap it?

@csmartinsfct @kyledewy @cryptnotiq @AspacehUK please take a look at it.

**Comment by pacamara** [comment]
@jjperezaguinaga You're very welcome, cheers for the feedback! :beers: 

Staging deployment :  **https://dropzone-pr4-staging.herokuapp.com**

It now airdrops the official MYB ropsten token,   [0xbb07c8c6e7cd15e2e6f944a5c2cac056c5476151](https://ropsten.etherscan.io/address/0xbb07c8c6e7cd15e2e6f944a5c2cac056c5476151) , same as MyBit-Trust, and same as given out by faucet. (Previously was deploying a separate token).

Have just realized it serves blank page if metamask not installed, will fix!

**Comment by pacamara** [comment]
Now the code is [live on dropzone.mybit.io](https://dropzone.mybit.io), will shutdown the staging instance.

**Pull request merged**
